version: '3.7'

services:
  webserver:
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./dags:/root/airflow/dags
  db:
    image: mysql:5.7
    volumes:
      - db:/var/lib/mysql
    ports:
      - $DOCKER_HOST_DB_PORT:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
volumes:
  db:
    driver: local